### ISSUE TITLE
SyntaxTextView as its own lib?

### ISSUE THREAD

**Issue by rnystrom** [louisdh/savannakit#2]
Looks slick! Are there any plans to pull this out into its own library? Would love to try it in [GitHawk](https://github.com/GitHawkApp/GitHawk/issues/1642).

**Comment by louisdh** [comment]
Hmm, why would SyntaxTextView need its own library? What prevents you from using SavannaKit in GitHawk?

Please note, SavannaKit's goal is to be "A protocol oriented framework for creating IDEs for iOS and macOS". So I get that there might be some features added in future releases that you wouldn't necessarily need in GitHawk, but I don't feel the need to split SavannaKit in multiple frameworks.

**Comment by rnystrom** [comment]
True! I guess it doesn’t need its own lib, this one is pretty light.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
